# Generated by Django 3.1.6 on 2021-03-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist_username',
            field=models.CharField(default='', max_length=64),
        ),
    ]
