# Generated by Django 3.1.6 on 2021-03-05 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('starting_bid', models.IntegerField()),
                ('img_url', models.CharField(blank=True, max_length=64)),
                ('current_price', models.IntegerField(blank=True)),
                ('is_active', models.BooleanField()),
                ('category_id', models.ManyToManyField(blank=True, related_name='listing', to='auctions.Category')),
                ('current_winner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_bid', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ManyToManyField(blank=True, related_name='listing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
