# Generated by Django 3.1.6 on 2021-03-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='category_i',
            new_name='category_id',
        ),
    ]
