# Generated by Django 3.1.6 on 2021-03-06 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_seller_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_id',
        ),
    ]
