# Generated by Django 3.1.6 on 2021-03-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_watchlist_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlist_username',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
