# Generated by Django 3.1.6 on 2021-03-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='in_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
