# Generated by Django 3.1.6 on 2021-03-05 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210305_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_winner',
        ),
        migrations.AddField(
            model_name='listing',
            name='current_winner',
            field=models.ManyToManyField(blank=True, related_name='won_bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
