# Generated by Django 3.1.6 on 2021-03-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210305_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
