# Generated by Django 3.1.6 on 2021-03-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_current_winner_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_winner_username',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
