# Generated by Django 3.1.6 on 2021-03-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210310_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='listing_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
