# Generated by Django 3.1.6 on 2021-03-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210310_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listing_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='listing_id',
            field=models.ManyToManyField(blank=True, related_name='commented_on', to='auctions.Listing'),
        ),
    ]
