# Generated by Django 3.1.6 on 2021-03-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210310_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('art', 'Art'), ('other', 'Other'), ('', '')], default='', max_length=64),
        ),
    ]
